### PR TITLE
Fix monolith statewide header link

### LINKED ISSUE #516: Official website of the State of California - link not correct
On cannabis.ca.gov production - the text link doesn't link to ca.gov.
(Reported by Moorea Warren, DCC in meeting)

This issue comes from the WordPress theme. Need to research how this feature is constructed and come up with a recommended fix.

### PR DESCRIPTION
**Pull request by xjensen**
Fixes #516. 

There's now a JS implementation of the header's text ("Official website of the State of California"), which inserts that content directly into the DOM. I left the CSS implementation of that text in place too, just in case JS is disabled for some reason. We've established that it's messy and temporary, and I've made it a little messier here.

I don't know anything about how to test this on Flywheel. I'm not sure if I have access either. If my services are needed in that capacity, I'll need some help.

Also, let me know if I got the versioning of these monolith files incorrect. I didn't see any build tools or notes, so I just did it manually.

### CODE REVIEW

**Comment by chachasikes** [comment]
This looks good.

To test it: I added an account for you on api.cannabis.ca.gov.

Go to: https://api.cannabis.ca.gov/wp-admin/admin.php?page=caweb_options
Custom JS
Custom CSS

You can replace the relevant files to test your change fully integrated:
Here is what the CSS looks like. 
* Click the red X to remove just the file you don't want 
* Upload a new file
* Save changes
* At this point the file should update.

Every once it a while the cache may get stuck, in which case, you can add another point version to increment the file.
Screen Shot 2022-07-21 at 2 07 50 PM


_monolith is our bucket. It contains code that Aaron & Konstantin worked on.

Your versioning guess is correct.

**Comment by chachasikes** [comment]
@xjensen Let me know if you are able to successfully test the code on api.cannabis.ca.gov & then I can approve this. Thank you!

**Comment by chachasikes** [comment]
When it's ready, I will upload it to production.

**Comment by chachasikes** [comment]
Here's a README for the files that I know we are using.

The others are archival in case we need to pull Aaron or Konstantin back in on the Design System style overlay.

https://github.com/cagov/cannabis.ca.gov/blob/main/_monolith/README.md

**Comment by xjensen** [comment]
Thanks, @chachasikes, very helpful. 

I've uploaded the new CSS and JS into api.cannabis.ca.gov. It's looking good and ready. The new version number for each is 1.0.4.

Under CAWeb Options, I needed to toggle on the Home Link (General Settings > Utility Header > Home Link). I'm assuming that's already activated on the production site.

**Comment by chachasikes** [comment]
Correct, it is enabled on production already. Thank you so much. Will upload later this afternoon.

**Pull request merged**
