### PR TITLE
major version bumps of components and add pagination to announcements

### PR DESCRIPTION
**Pull request by aaronhans**
- Integrate the major version bumps of the web components in the design system 
  - CSS for a couple of these components was removed because it is delivered in the js with no flash of unstyled content issues
- Used vscode sort function to alphabetize the scripts in the package.json (No other changes there)
- Add pagination to the announcements page. This is done via:
  -  A new 11ty data collection that is built using the existing get posts method from the post-list component
  - Adding the pagination custom element to the post list HTML
  - Adding a new template that returns post list html based on the paged collection. This HTML is built using the existing HTML creation method used for page 1
  - Client side code to listen for pagination click events, then get next page and change url to signify which page is being viewed

### CODE REVIEW

**Comment by aaronhans** [comment]
These changes are made to restore functionality with minimal code movement. It would be interesting to continue discussing isomorphic approaches for components like this in the future.

**Review by zakiya — APPROVED** [review]
Can you also update the readme with the new/changed npm script descriptions and advice? I thought we had pr environments on cannabis?

**Comment by aaronhans** [comment]
Thanks for mentioning that @zakiya the readmes in the components have the css inclusion step removed now in https://github.com/cagov/design-system/pull/366

**Comment by zakiya** [comment]
Thanks @aaronhans I was also referring to the global readme for this project. In general I'd like to see more documentation around our npm scripts so there are clear directives for developers.

**Comment by aaronhans** [comment]
I added a section to this readme, let me know how that looks. Thanks @zakiya

**Pull request merged**
