### PR TITLE
1.1.1 merge that octopus events

### PR DESCRIPTION
**Pull request by chachasikes**
Fix connections that were broken in merge to: header menu, css of menu, breadcrumbs, page layouts
Add event list code 

(next: test sort order with multiple events - see why there is a flash of what might be draft content)

### CODE REVIEW

**Comment by aaronhans** [comment]
This looks great Chach! Awesome work sorting all this out 

Few minor issues that could be addressed separately
- search results pointing at drought
- homepage link grid looks better 3x2
- missing icon in homepage page alert

**Review by aaronhans — APPROVED** [review]

**Comment by chachasikes** [comment]
Thanks Aaron

* search results pointing at drought -> good call, porting in jon's work on this - will look to connect it to the config file if that makes sense
* homepage link grid looks better 3x2 -> will compare to see what you mean here
* missing icon in homepage page alert -> yeah, let's see where it went, there was a font file - maybe its missing in the new version

Also
* fix(ing) the event listing (which is new) for parity with production
* missing linkedin & email icons - drought switched to icons, but old version used the font - this isn't compatible - but we should be able to create an SVG  & store it the same way as the other assets

**Comment by chachasikes** [comment]
* There is also a .json file conflict here to resolve

**Comment by chachasikes** [comment]
Got all the issues and a couple other little things
* New SVG icons (synced with Adam) 24x24, exported to SVG in Figma from the icon frame.

Fixed:
* Star icon fixed in page alert
* Event list fixed, templatized and sort order handled
* Added missing single-column-wide CSS style & made PR for design system to have it added to base-css.
* Grid layout fixed
* SVG added in passthrough code
* Search reconnect (note: tried to add it into config but the config.js is not accessible in JS scope from seach.njk - not sure why - 11ty has a few magical properties (& I think we ought to spend a week focusing just on team 11ty skills cause its render model is a little different)

**Pull request merged**
