### PR TITLE
testing install all the new beta versions

### PR DESCRIPTION
**Pull request by aaronhans**
This PR installs the latest versions of all components after they were updated to conform to our linting standards and to include unit tests

This has been tested locally on headless cannabis using mac Chrome & Safari, Chrome on Android and Safari on iPad

### CODE REVIEW

**Comment by xjensen** [comment]
The one thing I'd change, based on my publications to npm last night, is the version of ds-regulatory-outline. There was some weirdness with the version history and tags on that package. So I [published it as 1.0.1](https://www.npmjs.com/package/@cagov/ds-regulatory-outline). Hope this is okay. Lemme know if I should roll it back and republish as 0.0.3.

**Review by kkoryaka — APPROVED** [review]
Nice! Bumping to the latest and greatest

**Comment by aaronhans** [comment]
Thanks, regulatory outline major version bumped

**Comment by zakiya** [comment]
@xjensen Let me know if there's anything I should do differently when publishing packages.  ds-regulatory-outline was my first of two total npm packages and am happy to change my approach.

**Comment by xjensen** [comment]
@zakiya The confusion came from having a 1.0.0 published first, then a 0.0.2 published later (with the `latest` tag in npm), and then a version number of 1.0.1 in the codebase. Not sure how that all played out, but it wasn't a crisis or anything. The [process we discussed this morning](https://github.com/cagov/odi-engineering/wiki/How-to-publish-a-package-to-npm) in Slack should be a good process to follow going forward.

**Pull request merged**
