### PR TITLE
484 combobox internal search

### PR DESCRIPTION
**Pull request by zakiya**
This PR should complete the work on the comboxbox.

- [Here is a preview for QA](https://deploy-preview-5--nifty-turing-0ad445.netlify.app/cannabis-laws/where-cannabis-businesses-are-allowed/)

- I did **not** include the compiled files. They are:

     - src/js/charts/cannabis-local-ordinances/build/bundle.js
     - src/js/charts/cannabis-local-ordinances/build/assets/bundle.1.1.19-alt-no-combo-box.js
     - src/js/charts/cannabis-local-ordinances/src/js/combobox-places/src/css/index.css.map

- The exact markup I used to generate the test link is [here](https://github.com/zakiya/cagov-tests/blob/cannabis-475/covid19-clone/src--templates--wordpress--pages--where-cannabis-businesses-are-allowed.html). It replaces src/templates/wordpress/pages/where-cannabis-businesses-are-allowed.html

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
nice update, thanks for pointing out the cool SASS variable helper

**Comment by chachasikes** [comment]
I made some progress on the logic tables & QA testing documentation for this today. Still need to go over those with Liz (to try to build some automated testing)

In the process of planning and describing the tests, I noticed a little bug - the close button would not hide the select dropdown. To create this, I selected a couple of places - and then was trying to get back to Statewide only view.

**Comment by chachasikes** [comment]
Update: We are still planning to use this, but want to set up testing first. Planning to include this change with another change that would change the map.

I included some of the kinds of tests of the features of combo-box - but would be good to make sure all the major features are described so we can also think of how to break it.

**Comment by zakiya** [comment]
I had already begun a test plan for this in Notion. [Here it is moved to Coda](https://coda.io/d/_dxZWnMw55WU/Map-interaction-test-plan_sutxv)

I don't think automated testing should be a blocker to launching this. I also think this would be a good opportunity to train Wes on doing functional QA.

I'm not sure what you mean about the close button hiding the select drop down. The x in the input is supposed to clear the selection. Perhaps you can share a video?

**Comment by jbum** [comment]
We should discuss this (seems to have been inactive since July?)

**Comment by jbum** [comment]
Closing - Zakiya has this work saved in https://github.com/cagov/design-system-contributed-components

**Pull request closed without merging**
