### PR TITLE
Event date filtering

### PR DESCRIPTION
**Pull request by chachasikes**
Make event date filter show recent events for a couple of days after the event. The current dates events were dropping off

### CODE REVIEW

**Review by jbum — APPROVED** [review]
👍

**Comment by chachasikes** [comment]
We can change this to:

    const today = new Date();
    const threeDaysAgo = new Date(today);
    threeDaysAgo.setDate(threeDaysAgo.getDate() - 3);

OG intention was to say "tomorrow"
but added a couple of days as a buffer so event is still up as a reference. We can check with DCC to find out their preference on timing.

**Comment by zakiya** [comment]
Would be good in the future to just leave a comment in the code since we may not have the capacity to get back to this right away and future us will probably forget.

**Comment by chachasikes** [comment]
I have the updated code in my local instance already. Will submit a follow up PR later today.

**Pull request merged**
